// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqQbjPFA_3fBrBuvNGb7riBkKtlJgTw8M',
    appId: '1:847615561635:web:b7b10dd6ab794e512d5416',
    messagingSenderId: '847615561635',
    projectId: 'tallersoftware-ab7d6',
    authDomain: 'tallersoftware-ab7d6.firebaseapp.com',
    storageBucket: 'tallersoftware-ab7d6.firebasestorage.app',
    measurementId: 'G-KZ9M6PVK31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1KuHg4N0c5KxcT_JhJpBHxni4mrYeEVQ',
    appId: '1:847615561635:android:6308f478a00d08672d5416',
    messagingSenderId: '847615561635',
    projectId: 'tallersoftware-ab7d6',
    storageBucket: 'tallersoftware-ab7d6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiqRo4S6XQJ7ATNKtSm7YDF_9Ydz4EIPg',
    appId: '1:847615561635:ios:c89f2bb900c31c302d5416',
    messagingSenderId: '847615561635',
    projectId: 'tallersoftware-ab7d6',
    storageBucket: 'tallersoftware-ab7d6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

}